### ISSUE TITLE
Events can only be associated with a single publisher

### ISSUE THREAD

**Issue by nwgallegos** [Particular/NServiceBus.MessagingBridge#272]
#### Description
Registering multiple publishers for the same event throws a System.InvalidOperationException stating "Events can only be associated with a single publisher"

#### Expected behavior
Events can be published from more than one endpoint, so registering publishers for the same event should be supported.

#### Actual behavior
An error occurs and only one endpoint can be registered as an event publisher.

#### Versions

Please list the version of the relevant packages or applications in which the bug exists.        
NServiceBus.Transport.Bridge 1.0.3 and NServiceBus.MessagingBridge 2.0.0

### Steps to reproduce

1. Download the [bridge sample](https://docs.particular.net/samples/bridge/simple/)
2. in the Program.cs file in the Bridge project, replace the 
    ```csharp
    rightReceiver.RegisterPublisher("OrderReceived", "Samples.Bridge.LeftSender");
    ```
    line with
    ```csharp
    rightReceiver.RegisterPublisher<OrderReceived>("Samples.Bridge.LeftSender");
    rightReceiver.RegisterPublisher<OrderReceived>("Samples.Bridge.RightReceiver");
    ```
3. Run the Bridge project and observe the exception.

### Relevant log output

```shell
/Users/nick/Downloads/simple_bridge_1_net6_0/Bridge/bin/Debug/net6.0/Bridge
Unhandled exception. System.InvalidOperationException: Events can only be associated with a single publisher, please verify subscriptions for:

- OrderReceived, Shared, Version=1.0.0.0, registered publishers: Samples.Bridge.LeftSender, Samples.Bridge.RightReceiver

   at NServiceBus.BridgeConfiguration.FinalizeConfiguration(ILogger`1 logger) in /_/src/NServiceBus.Transport.Bridge/Configuration/BridgeConfiguration.cs:line 120
   at NServiceBus.HostBuilderExtensions.<>c__DisplayClass1_1.<UseNServiceBusBridge>b__1(IServiceProvider sp) in /_/src/NServiceBus.Transport.Bridge/Configuration/HostBuilderExtensions.cs:line 48
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Program.Main() in /Users/nick/Downloads/simple_bridge_1_net6_0/Bridge/Program.cs:line 14
   at Program.<Main>()
```

#### Workarounds
None that I've found
#### Possible solutions
None that I've found - only registering one publisher isn't a solution because our system publishes events of the same type from multiple endpoints
#### Additional information
I'm currently trying to implement the new bridge package to help us transition our older azure service bus endpoints to amazon sqs.  Being unable to register multiple publishers means we'll have lost messages from the endpoints that can't be registered, unless I'm missing something.

**Comment by nwgallegos** [comment]
Update - this is also an issue with NServiceBus.MessagingBridge 2.0.0

**Comment by soujay** [comment]
@nwgallegos : An event is sent by one logical publisher and received by zero or more receivers. So, subscribing to an event that is published from multiple publishers will not be optimal.
Please elaborate more on your use case scenario for multiple publishers of same event.

**Comment by nwgallegos** [comment]
@soujay , In this particular case, we have a service that serves as an internal UI tool for managing or initiating batch jobs that we have. The batch jobs are not executed in the same service as the UI or in the same service as other batch jobs. In order for us to track when a job is completed and its status, each service publishes the same JobFinished event, allowing the service that hosts the UI to keep track in one central place. It isn't ideal, but it's what we have at the moment.

**Comment by soujay** [comment]
@nwgallegos - I agree with your reasoning about treating this as a bug as NServiceBus transports do not  restrict sending the same event from different publishers. Thank you for reporting it. This has been identified and marked as a bug and will be put in our queue. We will keep you updated on the progress.

**Comment by ramonsmits** [comment]
@nwgallegos can you reach out to us via <support@particular.net> and provide customer details? Depending on the type of support agreement we could prioritize this problem over other tasks.

**Comment by ramonsmits** [comment]
Fixed in https://github.com/Particular/NServiceBus.MessagingBridge/releases/tag/2.0.2

**Comment by nwgallegos** [comment]
@ramonsmits I appreciate the quick turnaround on this, however, I updated the package in the bridge sample and following the same steps am still getting an exception.  The exception is different, but still won't allow me to register multiple publishers of the same message: 
```
/Users/nick/Downloads/simple_bridge_1_net6_0/Bridge/bin/Debug/net6.0/Bridge 
- OrderReceived, Shared, Version=1.0.0.0, registered publishers: Samples.Bridge.LeftSender, Samples.Bridge.RightReceiverify subscriptions for:
   at NServiceBus.BridgeConfiguration.FinalizeConfiguration(ILogger`1 logger) in /_/src/NServiceBus.MessagingBridge/Configuration/BridgeConfiguration.cs:line 135
   at NServiceBus.HostBuilderExtensions.<>c__DisplayClass1_1.<UseNServiceBusBridge>b__1(IServiceProvider sp) in /_/src/NServiceBus.MessagingBridge/Configuration/HostBuilderExtensions.cs:line 48
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Program.Main() in /Users/nick/Downloads/simple_bridge_1_net6_0/Bridge/Program.cs:line 14
   at Program.<Main>()

```
I looks almost the same except there is now no custom error message explaining the issue at the beginning

**Comment by nwgallegos** [comment]
@ramonsmits , I spoke too soon. After looking through [the commits](https://github.com/Particular/NServiceBus.MessagingBridge/commit/d8508b2fb2866c79d39ca14e4892855ed8c95dc0) related to this, I noticed this:
```csharp
bridgeConfiguration.DoNotEnforceBestPractices();
```
After adding this, things are looking good. Thank you again.

**Comment by ramonsmits** [comment]
We've released https://github.com/Particular/NServiceBus.MessagingBridge/releases/tag/2.0.3 that reverted this enhancement and re-released this as part of https://github.com/Particular/NServiceBus.MessagingBridge/releases/tag/2.1.0
