### ISSUE TITLE
MessagingBridge.FailedQ headers is not reset on consecutive error

### ISSUE THREAD

**Issue by MarcWils** [Particular/NServiceBus.MessagingBridge#280]
#### Description
We have only just started using the MessagingBridge. We will initially use it to pull part of the load from our SQL database to another database. So we are going to use the Multi-Instance Mode setup. I hope to have this version up and running on production by the end of this month.

We have a little custom automation on top of the scripted retries. In that context, we are also testing whether this will also work well with messages that drop out from the messaging bridge. Whether and how often messages will fail is difficult to predict.

I tested it with version 2.0.1. The message can be returned but the behavior in the messaging bridge is different from how it normally works. If it were to fail again after retries, an ArgumentException would occur. The message already contains the `NServiceBus.MessagingBridge.FailedQ` header. And the code is going to try to add it again instead of overwriting it. We could remove that header when returning it to the source queue. But that would be different from how it normally works.

https://github.com/Particular/NServiceBus.MessagingBridge/blob/94c012310abe1ee4d7c40ca23636850ba60e938e/src/NServiceBus.MessagingBridge/RawEndpoints/RawEndpointErrorHandlingPolicy.cs#L38

#### Expected behavior
`MessagingBridge.FailedQ` header is succesfully updated on consecutive errors.

#### Actual behavior
`ArgumentException` when trying to add the `MessagingBridge.FailedQ` header when the message already contains such header.

#### Versions
NServiceBus.MessagingBridge 2.0.1

### Steps to reproduce

Trigger a persistent error in the bridge which causes a message to be forwarded to the error queue. Return the same message to the source queue. If the error still occurs, the bridge will try to move the same message back to the error queue.

### Relevant log output

```shell
System.ArgumentException:
   at System.ThrowHelper.ThrowArgumentException (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Collections.Generic.Dictionary`2.Insert (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at NServiceBus.Raw.RawEndpointErrorHandlingPolicy+<MoveToErrorQueue>d__5.MoveNext (NServiceBus.MessagingBridge, Version=2.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c: /_/src/NServiceBus.MessagingBridge/RawEndpoints/RawEndpointErrorHandlingPolicy.cs:39)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at NServiceBus.Transport.SqlServer.ProcessStrategy+<HandleError>d__8.MoveNext (NServiceBus.Transport.SqlServer, Version=7.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c: /_/src/NServiceBus.Transport.SqlServer/Receiving/ProcessStrategy.cs:63)
```

**Comment by ramonsmits** [comment]
Fixed in https://github.com/Particular/NServiceBus.MessagingBridge/releases/tag/2.0.2

**Comment by ThreePinkApples** [comment]
> Fixed in https://github.com/Particular/NServiceBus.MessagingBridge/releases/tag/2.0.2

This release is still not up on Nuget https://www.nuget.org/packages/NServiceBus.MessagingBridge/

**Comment by WilliamBZA** [comment]
2.0.2 was unlisted because it introduced another bug, 2.0.3 will be released with the correct fixes hopefully soon.

**Comment by WilliamBZA** [comment]
[2.0.3](https://www.nuget.org/packages/NServiceBus.MessagingBridge/2.0.3) has been released on nuget, this should be fixed again
