### ISSUE TITLE
Bridge can't transfer self-addressed messages in migration scenarios

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.MessagingBridge#474]
## Description

When the bridge tries to transfer messages between two transports it can do so only when the `ReplyToAddress` queue name exists on the target side. When the target address is not known to the bridge via endpoint registration on the source side, the message is moved to the bridge's error queue.

As a result, the Bridge is not able to transfer messages that have `ReplyToAddress` equal to the proxy queue address on the source side. This is true e.g. when the migrated endpoint is performing `SendLocal` operations.

## Who is affected

Users of the bridge who:
- Migrate endpoints that send messages to themselves e.g. via `SendLocal` 
- And, perform the migration with queues on the migration source side that contain such messages

## Symptoms

Messages with `ReplyToAddress` equal to the source queue address are moved to the error queue. The following error is logged by the bridge:

```code
System.Exception: Failed to shovel message for endpoint error with id <messageId> from <one-side> to <the-other-side>
 ---> System.Exception: No target address mapping could be found for source address: <source-address>. Ensure names have correct casing as mappings are case-sensitive. Nearest configured match: <closest-address>
```

## Steps to reproduce

- Set up the bridge with two transports. EndpointA on the left and EndpointB on the right side.
- Make EndpointA send messages to itself
- Add registration for EndpointA on the right side
- Bridge and EndpointA will become competing consumers on the EndpointsA queue. The messages picked up by the bridge will fail on processing and will be moved to the bridge's error queue on the left side. 

## Backported to
- [3.0.3](https://github.com/Particular/NServiceBus.MessagingBridge/pull/476)
- [2.2.3](https://github.com/Particular/NServiceBus.MessagingBridge/pull/473)

**Comment by mikesigs** [comment]
First off, thanks for opening this issue. Reading your reproduction steps kind of has me alarmed now. Does this mean the bridge is incapable of handling any SendLocal messages in the queue at the time the endpoint is moved to the right side?

**Comment by abparticular** [comment]
The fix is now available:
- [3.0.3](https://github.com/Particular/NServiceBus.MessagingBridge/releases/tag/3.0.3)
- [2.2.3](https://github.com/Particular/NServiceBus.MessagingBridge/releases/tag/2.2.3)

**Comment by NChaganlal** [comment]
Hi @mikesigs with the fix we've released, the bridge will be able to handle any SendLocal messages in the queue.

**Comment by mikesigs** [comment]
Thank you all for pushing this through so quickly!

**Comment by mikesigs** [comment]
I just had an opportunity to finally try the update. Using version 2.2.3 of the NServiceBus.MessagingBridge nuget package. Unfortunately I am still getting shovel failure messages.

```
System.Exception: Failed to shovel message for endpoint <<Redacted>> with id bfcedb98-1ee1-4a72-af2c-a9168555a2a5 from sl-nsb-bridge-sqlserver to sl-nsb-bridge-sqs
 ---> System.Exception: No target address mapping could be found for source address: <<Redacted>>@[dbo]@[NServiceBus.Transport]. Ensure names have correct casing as mappings are case-sensitive. Nearest configured match: <<Redacted>>@[dbo]@[NServiceBus.Transport]
   at EndpointRegistry.TranslateToTargetAddress(String sourceAddress) in /_/src/NServiceBus.MessagingBridge/EndpointRegistry.cs:line 67
   at MessageShovel.TransformRegularMessageReplyToAddress(TransferContext transferContext, OutgoingMessage messageToSend, IEndpointRegistry targetEndpointRegistry) in /_/src/NServiceBus.MessagingBridge/MessageShovel.cs:line 105
   at MessageShovel.TransferMessage(TransferContext transferContext, CancellationToken cancellationToken) in /_/src/NServiceBus.MessagingBridge/MessageShovel.cs:line 76
   --- End of inner exception stack trace ---
   at MessageShovel.TransferMessage(TransferContext transferContext, CancellationToken cancellationToken) in /_/src/NServiceBus.MessagingBridge/MessageShovel.cs:line 76
   at NServiceBus.Transport.SqlServer.ProcessStrategy.TryHandleMessage(Message message, TransportTransaction transportTransaction, ContextBag context, CancellationToken cancellationToken) in /_/src/NServiceBus.Transport.SqlServer/Receiving/ProcessStrategy.cs:line 53
   at NServiceBus.Transport.SqlServer.ProcessWithNativeTransaction.TryProcess(Message message, TransportTransaction transportTransaction, ContextBag context, CancellationToken cancellationToken) in /_/src/NServiceBus.Transport.SqlServer/Receiving/ProcessWithNativeTransaction.cs:line 119
```
